"""Cambiar documento de Integer a String

Revision ID: 9a698fc4b3d7
Revises: 8336ab9ba431
Create Date: 2025-12-01 18:18:28.997038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a698fc4b3d7'
down_revision = '8336ab9ba431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.alter_column('documento',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.alter_column('documento',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
